name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # Se ejecutará en cada push a la rama "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/hola-mundopy:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hola-mundopy:${{ github.sha }}